dockerce:
  oracle:
    version: 24.0.4-1.el9
  bookworm:
    version: 5:24.0.3-1~debian.12~bookworm
  jammy:
    version: 5:24.0.2-1~ubuntu.22.04~jammy
  focal:
    version: 5:20.10.8~3-0~ubuntu-focal
containerd:
  oracle:
    version: 1.6.21-3.1.el9
  bookworm:
    version: 1.6.21-1
  jammy:
    version: 1.6.21-1
  focal:
    version: 1.4.9-1