#!/bin/bash

if [[ "$DEVICE_IFACE" != "$MNIC" && "$DEVICE_IFACE" != *"docker"* && "$DEVICE_IFACE" != *"tun"* && "DEVICE_IFACE" != *"wg"* ]]; then
	for i in rx tx sg tso ufo gso gro lro; do
		ethtool -K "$DEVICE_IFACE" "$i" off;
  	done
	ip link set dev "$DEVICE_IFACE" arp off multicast off allmulticast off promisc on
fi
