#!/bin/bash

# Copyright 2014,2015,2016,2017,2018,2019,2020,2021 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Get the latest code
rm -rf /tmp/sohotfix
mkdir -p /tmp/sohotfix
cd /tmp/sohotfix
git clone https://github.com/Security-Onion-Solutions/securityonion
if [ ! -d "/tmp/sohotfix/securityonion" ]; then
  echo "I was unable to get the latest code. Check your internet and try again."
  exit 1
else
  echo "Looks like we have the code lets create the tarball."
  cd /tmp/sohotfix/securityonion
  tar cvf /tmp/sohotfix/sohotfix.tar HOTFIX VERSION salt pillar
  echo ""
  echo "Copy /tmp/sohotfix/sohotfix.tar to portable media and then copy it to your airgap manager."
  exit 0
fi