#!/bin/bash
#
# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at 
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.

. /usr/sbin/so-common

if [[ $# -lt 1 ]]; then
	echo "Submit a cURL request to the local Security Onion Elasticsearch host."
	echo ""
	echo "Usage: $0 <PATH> [ARGS,...]"
	echo ""
  echo "Where "
  echo "   PATH represents the elastic function being requested."
  echo "   ARGS is used to specify additional, optional curl parameters."
  echo ""
  echo "Examples:"
  echo "   $0 /"
  echo "   $0 '*:so-*/_search' -d '{\"query\": {\"match_all\": {}},\"size\": 1}' | jq"
  exit 1
fi

QUERYPATH=$1
shift

curl -K /opt/so/conf/elasticsearch/curl.config -s -k -L -H "Content-Type: application/json" "https://localhost:9200/${QUERYPATH}" "$@"
