#!/bin/bash

. /usr/sbin/so-common

usage() {
  read -r -d '' message <<- EOM
		usage: so-monitor-add [-h] NIC

    positional arguments:
      NIC           The interface you want to add to the monitor bond

    optional arguments:
      -h, --help    Show this help message and exit
	EOM
  echo "$message"
  exit 1
}

if [[ $# -eq 0 || $# -gt 1 ]] || [[ $1 == '-h' || $1 == '--help' ]]; then
  usage
fi

add_interface_bond0 "$1"
