#!/bin/bash

# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.

. /usr/sbin/so-common

echo "Requires: An active SOC license."
echo "This script is intended to leverage OSCAPs built in remediate function to apply STIGs. This is currently experimental and may result in having to rebuild this SO node."

read -p "Do you want to continue? yes / no: " response

case "$response" in
    yes)
        echo "Applying oscap saltstate..."
        salt-call state.apply oscap
        echo "Current oscap report can be found in /opt/so/log/oscap"
        ;;
    *)
        echo "Exiting"
        ;;
esac