#!/bin/bash
#
# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at 
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.



if [ $# -lt 2 ]; then
  echo "Usage: $0 <steno-query> Output-Filename"
  exit 1
fi

docker exec -it so-sensoroni scripts/stenoquery.sh "$1" -w /nsm/pcapout/$2.pcap

echo ""
echo "If successful, the output was written to: /nsm/pcapout/$2.pcap"
