#!/bin/bash

# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at 
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.



# Usage: so-stop  filebeat | kibana | playbook | thehive

. /usr/sbin/so-common

if [ $# -ge 1 ]; then
	echo $banner
	printf "Stopping $1...\n"
	echo $banner

	case $1 in
    		*) docker stop so-$1 ; docker rm so-$1 ;;
	esac
else
	echo -e "\nPlease provide an argument by running like so-stop $component, or by using the component-specific script.\nEx. so-stop filebeat, or so-filebeat-stop\n"	
fi

