#!/bin/bash

# Copyright 2014,2015,2016,2017,2018,2019,2020 Security Onion Solutions, LLC
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Usage: so-test

. /usr/sbin/so-common

REPLAY_ENABLED=$(docker images | grep so-tcpreplay)
REPLAY_RUNNING=$(docker ps | grep so-tcpreplay)

if  [ "$REPLAY_ENABLED" != "" ] && [ "$REPLAY_RUNNING" != "" ]; then
   docker cp so-tcpreplay:/opt/samples /opt/samples
   docker exec -it so-tcpreplay /usr/local/bin/tcpreplay -i bond0 -M10 /opt/samples/*
   echo
   echo "PCAP's have been replayed - it is normal to see some warnings."
   echo
else
  echo "Replay functionality not enabled!  Enabling Now...."
  echo
  echo "Note that you will need internet access to download the appropriate components"
  /usr/sbin/so-start tcpreplay
  echo "Replay functionality enabled.  Replaying PCAPs Now...."
  docker cp so-tcpreplay:/opt/samples /opt/samples
  docker exec -it so-tcpreplay /usr/local/bin/tcpreplay -i bond0 -M10 /opt/samples/*
  echo
  echo "PCAP's have been replayed - it is normal to see some warnings."
  echo
fi

