#!/bin/bash

# Copyright 2014,2015,2016,2017,2018,2019,2020,2021 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Show Zeek stats (capstats, netstats)

show_stats() {
  echo '##############'
  echo '# Zeek Stats #'
  echo '##############'
  echo
  echo "Average throughput:"
  echo
  docker exec -it so-zeek "runuser -l zeek -c '/opt/zeek/bin/zeekctl capstats'"
  echo
  echo "Average packet loss:"
  echo
  docker exec -it so-zeek "runuser -l zeek -c '/opt/zeek/bin/zeekctl netstats'"
  echo
}

if docker ps | grep -q zeek; then
  show_stats
else
  echo "Zeek is not running! Try starting it with 'so-zeek-start'." && exit 1;
fi
