#!/bin/bash
# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.

. /usr/sbin/so-common

# Initial Endpoints
for INTEGRATION in /opt/so/saltstack/default/salt/elasticfleet/files/integrations/endpoints-initial/*.json
do
  printf "\n\nInitial Endpoint Policy - Loading $INTEGRATION\n"
  elastic_fleet_integration_create "@$INTEGRATION"
done

# Grid Nodes
for INTEGRATION in /opt/so/saltstack/default/salt/elasticfleet/files/integrations/grid-nodes/*.json
do
  printf "\n\nGrid Nodes Policy - Loading $INTEGRATION\n"
  elastic_fleet_integration_create "@$INTEGRATION"
done