#!/bin/bash

. /usr/sbin/so-common

argstr=""
for arg in "$@"; do
    argstr="${argstr} \"${arg}\""
done

docker exec so-idstools /bin/bash -c "cd /opt/so/idstools/etc && idstools-rulecat --force ${argstr}"
