#!/bin/bash

. /usr/sbin/so-common

# Pull down the latest rules if not airgap

docker exec so-idstools idstools-rulecat -v --suricata-version 6.0 -o /nsm/rules/suricata/ --force

argstr=""
for arg in "$@"; do
    argstr="${argstr} \"${arg}\""
done

docker exec so-idstools /bin/bash -c "cd /opt/so/idstools/etc && idstools-rulecat --force ${argstr}"
