#!/bin/bash
#
# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at 
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.
{% from 'vars/globals.map.jinja' import GLOBALS -%}
{% if GLOBALS.has_mom -%}
{%   set CONFIGFILE='/etc/yum.repos.d/securityonion.repo' -%}
{%   set REPOID='securityonion' -%}
{%   set CHECKUP=false -%}
{% else -%}
{%   set CONFIGFILE='/opt/so/conf/reposync/repodownload.conf' -%}
{%   set REPOID='securityonionsync' -%}
{%   set CHECKUP=true -%}
{% endif -%}
NOROOT=1
. /usr/sbin/so-common

set_version
set_os
salt_minion_count

set -e

{% if CHECKUP -%}
curl --retry 5 --retry-delay 60 -A "reposync/$VERSION/$OS/$(uname -r)/$MINIONCOUNT" https://sigs.securityonion.net/checkup --output /tmp/checkup
{% endif -%}
dnf reposync --norepopath -g --delete -m -c {{CONFIGFILE}} --repoid={{REPOID}} --download-metadata -p /nsm/repo/
createrepo /nsm/repo
