#!/bin/bash

# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at 
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.

local_salt_dir=/opt/so/saltstack/local

if [[ -f /usr/sbin/so-common ]]; then
  source /usr/sbin/so-common
else
  source $(dirname $0)/../../../common/tools/sbin/so-common
fi

if ! grep -q "^  kafka_cluster_id:" $local_salt_dir/pillar/secrets.sls; then
    kafka_cluster_id=$(get_random_value 22)
    echo '  kafka_cluster_id: '$kafka_cluster_id >> $local_salt_dir/pillar/secrets.sls
fi

if ! grep -q "^  kafkapass:" $local_salt_dir/pillar/secrets.sls; then
    kafkapass=$(get_random_value)
    echo '  kafkapass: '$kafkapass >> $local_salt_dir/pillar/secrets.sls
fi