#!/bin/bash

# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at 
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.

local_salt_dir=/opt/so/saltstack/local

if [[ -f /usr/sbin/so-common ]]; then
  source /usr/sbin/so-common
else
  source $(dirname $0)/../../../common/tools/sbin/so-common
fi

if ! grep -q "^  cluster_id:" $local_salt_dir/pillar/kafka/soc_kafka.sls; then
    kafka_cluster_id=$(get_random_value 22)
    echo 'kafka: ' > $local_salt_dir/pillar/kafka/soc_kafka.sls
    echo '  cluster_id: '$kafka_cluster_id >> $local_salt_dir/pillar/kafka/soc_kafka.sls
else
    echo 'kafka:cluster_id pillar exists'
    salt-call pillar.get kafka:cluster_id
fi
