#!/bin/bash
#
# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at 
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.
NOROOT=1
. /usr/sbin/so-common

set -e

curl --retry 5 --retry-delay 60 -A "reposync/$(sync_options)" https://sigs.securityonion.net/checkup --output /tmp/checkup
dnf reposync --norepopath -g --delete -m --newest-only -c /opt/so/conf/reposync/repodownload.conf --repoid=securityonionsync --download-metadata -p /nsm/repo/

DOCKERCE=$(grep -A2 'dockerce' $DEFAULT_SALT_DIR/salt/docker/version.yaml | grep -A1 'oracle' | grep -v 'oracle' | sed 's/^.*version: //')
CONTAINERD=$(grep -A2 'containerd' $DEFAULT_SALT_DIR/salt/docker/version.yaml | grep -A1 'oracle' | grep -v 'oracle' | sed 's/^.*version: //')
LOCKED_PKGS=(
  	"docker-ce-$DOCKERCE"
	"docker-ce-cli-$DOCKERCE"
	"docker-ce-rootless-extras-$DOCKERCE"
	"containerd.io-$CONTAINERD"
)
dnf download -c /opt/so/conf/reposync/repodownload.conf --repoid=securityonionsync --downloaddir=/nsm/repo/ "${LOCKED_PKGS[@]}"
dnf download -c /opt/so/conf/reposync/repodownload.conf --repoid=securityonionsync --downloaddir=/nsm/repo/ "salt*"
createrepo /nsm/repo
