reactor:
  - 'salt/beacon/*/inotify//opt/so/saltstack/local/salt/suricata/rules/':
    - salt://reactor/push_suricata.sls
  - 'salt/beacon/*/inotify//opt/so/saltstack/local/salt/strelka/rules/compiled/':
    - salt://reactor/push_strelka.sls
  - 'salt/beacon/*/inotify//opt/so/saltstack/local/pillar/':
    - salt://reactor/push_pillar.sls
