reactor:
  - 'salt/beacon/*/inotify//opt/so/saltstack/local/salt/suricata/rules':
    - salt://reactor/push_suricata.sls
  - 'salt/beacon/*/inotify//opt/so/saltstack/local/salt/suricata/rules/*':
    - salt://reactor/push_suricata.sls
  - 'salt/beacon/*/inotify//opt/so/saltstack/local/salt/strelka/rules/compiled':
    - salt://reactor/push_strelka.sls
  - 'salt/beacon/*/inotify//opt/so/saltstack/local/salt/strelka/rules/compiled/*':
    - salt://reactor/push_strelka.sls
  - 'salt/beacon/*/pillar_db/audit_settings':
    - salt://reactor/push_pillar.sls
