#!/bin/bash
#
# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at 
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.


. /usr/sbin/so-common

if [ "$1" == "" ]; then
        curl -s -L http://localhost:9600/_node/stats | jq .pipelines 
else
        curl -s -L http://localhost:9600/_node/stats | jq .pipelines.$1
fi
