{
 "title": "Standalone Mode - {{ SERVERNAME }} Overview",
 "description": "This Dashboard provides a general overview of Standalone Mode",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "10s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "{{ SERVERNAME }} - CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "mean_usage_idle" ], "type": "field" },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - System Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - ES CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / {{ CPUS }}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-elasticsearch" }
     ]
    },
    {
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "mean_usage_percent" ], "type": "field" },
       { "params": [ "/16" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-elasticsearch" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Kibana CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / {{ CPUS }}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "so-kibana" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "mean_usage_percent" ], "type": "field" },
       { "params": [ "/16" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "so-kibana" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Suricata Packet Loss",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "suridrop",
     "select": [
      [
       { "params": [ "drop" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - PCAP Packet Loss",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stenodrop",
     "select": [
      [
       { "params": [ "drop" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Disk Used(/)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    },
    {
     "measurement": "disk",
     "select": [
      [
       { "params": [ "mean_used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Disk Used(/nsm)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/nsm" }
     ]
    },
    {
     "measurement": "disk",
     "select": [
      [
       { "params": [ "mean_used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/nsm" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - InfluxDB CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / {{ CPUS }}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-influxdb" }
     ]
    },
    {
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "mean_usage_percent" ], "type": "field" },
       { "params": [ "/16" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-influxdb" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Logstash CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / {{ CPUS }}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-logstash" }
     ]
    },
    {
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "mean_usage_percent" ], "type": "field" },
       { "params": [ "/16" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-logstash" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Suri CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / {{ CPUS }}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-suricata" }
     ]
    },
    {
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "mean_usage_percent" ], "type": "field" },
       { "params": [ " / {{ CPUS }}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-suricata" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Steno CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / {{ CPUS }}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-steno" }
     ]
    },
    {
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "mean_usage_percent" ], "type": "field" },
       { "params": [ "/16" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-steno" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Percent(%)" }
   ],
   "targets": [
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Interrupt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Wait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "SoftIRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Management Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bps", "label": "Bits/Sec" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT 8 * non_negative_derivative(mean(\"bytes_recv\"),1s) FROM \"net\" WHERE \"host\" = 'JumpHost' AND \"interface\" = 'eth0' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "{{ MANINT }}" }
     ]
    },
    {
     "alias": "Outbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT 8 * non_negative_derivative(mean(\"bytes_sent\"),1s) FROM \"net\" WHERE \"host\" = 'JumpHost' AND \"interface\" = 'eth0' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "{{ MANINT }}" }
     ]
    },
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "mean_bytes_recv" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "{{ MANINT }}" }
     ]
    },
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "mean_bytes_sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "{{ MANINT }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Suri Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-suricata" }
     ]
    },
    {
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "mean_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-suricata" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Steno Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-steno" }
     ]
    },
    {
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "mean_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-steno" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "#cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "alias": "1 Minute Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "alias": "5 Minute Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "alias": "15 Minute Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Monitor Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bps", "label": "Bits/Sec" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT 8 * non_negative_derivative(mean(\"bytes_recv\"),1s) FROM \"net\" WHERE \"host\" = 'JumpHost' AND \"interface\" = 'eth0' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "{{ MONINT }}" }
     ]
    },
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "mean_bytes_recv" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "{{ MONINT }}" }
     ]
    }
   ]
  },
  {
   "title": "Zeek Restarts via Healthcheck",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "healthcheck",
     "select": [
      [
       { "params": [ "zeek_restart" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - PCAP Retention",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Oldest Pcap",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcapage",
     "select": [
      [
       { "params": [ "seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "measurement": "pcapage",
     "select": [
      [
       { "params": [ "mean_seconds" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "alias": "Sleep",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "sleeping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Logstash Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "Bits/Sec" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-logstash" }
     ]
    },
    {
     "alias": "Outbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-logstash" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Zeek CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / {{ CPUS }}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-zeek" }
     ]
    },
    {
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "mean_usage_percent" ], "type": "field" },
       { "params": [ "/16" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-zeek" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Zeek Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-zeek" }
     ]
    },
    {
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "mean_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-zeek" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Total Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - InfluxDB Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "bps", "label": "Bits/Sec" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-influxdb" }
     ]
    },
    {
     "alias": "Outbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-influxdb" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Zeek Capture Loss",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zeekcaptureloss",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Zeek Packet Loss",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zeekdrop",
     "select": [
      [
       { "params": [ "drop" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - IO Wait",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Proxy Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "bps", "label": "Bits/Sec" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-aptcacherng" }
     ]
    },
    {
     "alias": "Outbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-aptcacherng" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - InfluxDB Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxsize",
     "select": [
      [
       { "params": [ "kbytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "measurement": "influxsize",
     "select": [
      [
       { "params": [ "mean_kbytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Redis Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "redisqueue",
     "select": [
      [
       { "params": [ "unparsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "measurement": "redisqueue",
     "select": [
      [
       { "params": [ "mean_unparsed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Estimated EPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "EPS" }
   ],
   "targets": [
    {
     "alias": "EPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "esteps",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "measurement": "esteps",
     "select": [
      [
       { "params": [ "mean_eps" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Redis Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-redis" }
     ]
    },
    {
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "mean_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-redis" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Redis CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ 16" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-redis" }
     ]
    },
    {
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "mean_usage_percent" ], "type": "field" },
       { "params": [ "/16" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" },
      { "condition": "AND", "key": "container_name", "operator": "=", "value": "so-redis" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "alias": "Buffered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - ES Documents",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "docs_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - ES Store Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "store_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "mean_store_size_in_bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - ES Thread Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "threads_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "mean_threads_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - ES Fielddata Cache Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "fielddata_memory_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "measurement": "elasticsearch_indices",
     "select": [
      [
       {
        "params": [
         "mean_fielddata_memory_size_in_bytes"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  },
  {
   "title": "{{ SERVERNAME }} - Memory(Used)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "{{ SERVERNAME }}" }
     ]
    }
   ]
  }
 ]
}