#!/bin/bash

readonly create_bond_str='Creating bond interface'
export create_bond_str

readonly salt_install_str='Installing Salt and dependencies'
export salt_install_str

readonly docker_install_str='Installing Docker'
export docker_install_str

readonly salt_minion_init_str='Initializing Salt minion'
export salt_minion_init_str

readonly gen_patch_pillar_str='Generating the patch pillar'
export gen_patch_pillar_str

readonly gen_static_pillar_str='Generating the static pillar'
export gen_static_pillar_str

readonly gen_master_pillar_str='Generating the master pillar'
export gen_master_pillar_str

readonly copy_temp_minion_str='Copying minion pillars to master'
export copy_temp_minion_str