#!/bin/bash

#so-fleet-packages $MasterIP $FleetEmail

esecret=$(docker exec so-fleet fleetctl get enroll-secret)

#Concat fleet.crt & ca.crt  - this is required for launcher connectivity
cat /etc/pki/fleet.crt /etc/pki/ca.crt > /etc/pki/launcher.crt

#Create the output directory
mkdir /opt/so/conf/fleet/packages

#At some point we should version launcher `latest` to avoid hard pinning here
docker run \
  --rm \
  --mount type=bind,source=/opt/so/conf/fleet/packages,target=/output \
  --mount type=bind,source=/etc/pki/launcher.crt,target=/var/launcher/launcher.crt \
  docker.io/soshybridhunter/so-fleet-launcher:HH1.1.0 "$esecret" "$1":8080

cp /opt/so/conf/fleet/packages/launcher.* /opt/so/saltstack/salt/launcher/packages/
#Update timestamp on packages webpage
sed -i "s@.*Generated.*@Generated: $(date '+%m%d%Y')@g" /opt/so/conf/fleet/packages/index.html
sed -i "s@.*Generated.*@Generated: $(date '+%m%d%Y')@g" /opt/so/saltstack/salt/fleet/osquery-packages.html
#####